proy_sales/core/urls.py
from django.urls import include, path
from core import views
 
app_name='core' # define un espacio de nombre para la aplicación
urlpatterns = [    
    path('', views.home, name='home'),  # Página de inicio para todos los usuarios'

    # Otras URLs
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),

    # URLs de vistas
    path('product_list/', views.product_List,name='product_list'),
    path('product_create/', views.product_create,name='product_create'),
    path('product_update/<int:id>/', views.product_update,name='product_update'),
    path('product_delete/<int:id>/', views.product_delete,name='product_delete'),

    # URLs de marcas
    path('brand_list/', views.brand_List,name='brand_list'),
    path('brand_create/', views.brand_create,name='brand_create'),
    path('brand_update/<int:id>/', views.brand_update,name='brand_update'),
    path('brand_delete/<int:id>/', views.brand_delete,name='brand_delete'),

    # URLs de proveedores
    path('supplier_list/', views.supplier_List,name='supplier_list'),
    path('supplier_create/', views.supplier_create,name='supplier_create'),
    path('supplier_update/<int:id>/', views.supplier_update,name='supplier_update'),
    path('supplier_delete/<int:id>/', views.supplier_delete,name='supplier_delete'),

    # URLs de categorías
    path('category_list/', views.category_List,name='category_list'),
    path('category_create/', views.category_create,name='category_create'),
    path('category_update/<int:id>/', views.category_update,name='category_update'),
    path('category_delete/<int:id>/', views.category_delete,name='category_delete'),
    
    path('purchase/', include('purchase.urls')),
]

proy_sales/proy_sales/urls.py
from django.conf import settings
from django.conf.urls.static import static
from core import views as core 
from django.contrib import admin
from django.urls import path,include
from core import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),

    path('signup/', core.signup, name='signup'),
    path('logout/', core.signout, name='logout'),
    path('signin/', core.signin, name='signin'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),


    path('', include('core.urls',namespace='core')),
    path('purchase/', include('purchase.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proy_sales/core/models.py
import datetime
from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from proy_sales.utils import phone_regex, valida_cedula, valida_numero_flotante_positivo, valida_numero_entero_positivo

class CustomUser(AbstractUser):
    dni = models.CharField(max_length=10,unique=True,validators=[valida_cedula])
    full_name = models.CharField(max_length=100)
    celular = models.CharField(max_length=10,blank=True, null=True,validators=[phone_regex])
    correo = models.EmailField(blank=True, null=True)
    imagen = models.ImageField(upload_to='imagenes_perfil/', null=True, blank=True)


    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    def get_profile_picture_url(self):
        if self.imagen:
            return self.imagen.url
        else:
            return None

    def __str__(self):
        return self.username
    
class Brand(models.Model):
    description = models.CharField('Articulo', max_length=100,unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField('Estado', default=True)

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'
        ordering = ['description']
        indexes = [models.Index(fields=['description'])]

    def __str__(self):
        return self.description

class Supplier(models.Model):
    name = models.CharField(max_length=100, unique=True)
    ruc = models.CharField(max_length=10,validators=[valida_cedula],unique=True) 
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=10,validators=[phone_regex],unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField('Estado', default=True)
    image = models.ImageField(upload_to='suppliers/', blank=True, null=True)

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]

    def __str__(self):
        return self.name

class Category(models.Model):
    description = models.CharField('Categoría', max_length=100,unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField('Estado', default=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['description']
        indexes = [models.Index(fields=['description'])]

    def __str__(self):
        return self.description

def get_default_expiration_date():
    return timezone.now() + datetime.timedelta(days=30)

class Product(models.Model):
    class Status(models.TextChoices):
        STORE = 'RS', 'Rio Store'
        FERRISARITO = 'FS', 'Ferrisariato'
        COMISARIATO = 'CS', 'Comisariato'

    description = models.CharField(max_length=100,unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,validators=[valida_numero_flotante_positivo])
    stock = models.IntegerField(default=100,validators=[valida_numero_entero_positivo])
    expiration_date = models.DateTimeField(default=timezone.now() + datetime.timedelta(days=30))
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='product', verbose_name='Marca')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    supplier = models.OneToOneField(Supplier, on_delete=models.CASCADE, verbose_name='Proveedor')
    categories = models.ManyToManyField('Category', verbose_name='Categoria')
    line = models.CharField(max_length=2, choices=Status.choices)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    state = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['description']
        indexes = [models.Index(fields=['description']),]

    def __str__(self):
        return self.description

    @property
    def get_categories(self):
        return " - ".join([c.description for c in self.categories.all().order_by('description')])

proy_sales/core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from core.forms import ProductForm, BrandForm, SupplierForm, CategoryForm
from core.models import Product, Brand, Supplier, Category
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django .contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .forms import CustomUserCreationForm, CustomUserUpdateForm
from django.contrib import messages

# ----------------- Perfil -----------------
def profile(request):
    return render(request, 'core/profile.html')

#  Actualizar perfil 
def update_profile(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Tu perfil ha sido actualizado exitosamente!')
            return redirect('profile')
    else:
        form = CustomUserUpdateForm(instance=request.user)
    
    return render(request, 'core/update_profile.html', {'form': form})

# ----------------- Registro -----------------
def signup(request):
    data = {"title1": "Registro | TeacherCode",
            "title2": "Registro de Usuarios"}

    if request.method == "GET":
        form = CustomUserCreationForm()
        return render(request, "registration/signup.html", {"form": form, **data})
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # login(request, user)
            messages.success(
                request, '¡Registro exitoso! Por favor, inicia sesión.')
            return redirect("signin")
        else:
            # Manejo de errores específicos
            if form.errors:
                error_messages = []
                for field in form:
                    for error in field.errors:
                        error_messages.append(f"{field.label}: {error}")
                for error in form.non_field_errors():
                    error_messages.append(error)
                data["errors"] = error_messages

            return render(request, "registration/signup.html", {"form": form, **data})

# ----------------- Cerrar Sesion -----------------
def signout(request):
    logout(request)
    return redirect("core:home")

# ----------------- Iniciar Sesion -----------------
def signin(request):
    data = {"title1": "Inicio de Sesión | TeacherCode",
            "title2": "Inicio de Sesión"}

    if request.method == "GET":
        # Obtener mensajes de éxito de la cola de mensajes
        success_messages = messages.get_messages(request)
        return render(request, "registration/signin.html", {
            "form": AuthenticationForm(),
            "success_messages": success_messages,  # Pasar mensajes de éxito a la plantilla
            **data
        })
    else:
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("core:home")
            else:
                return render(request, "registration/signin.html", {
                    "form": form,
                    "error": "El usuario o la contraseña son incorrectos",
                    **data
                })
        else:
            return render(request, "registration/signin.html", {
                "form": form,
                **data
            })

# ----------------- Vistas de Home -----------------
def home(request):
    data = {"title1": "Autor | TeacherCode",
            "title2": "Super Mercado Economico"}
    # Obtener el estado de autenticación del usuario
    is_authenticated = request.user.is_authenticated
    # Agregar el estado de autenticación al contexto
    data["is_authenticated"] = is_authenticated
    return render(request, 'core/home.html', data)

# ----------------- Vistas de Productos -----------------
def product_List(request):
    data = {"title1": "Productos", "title2": "Consulta De Productos"}
    products = Product.objects.all()  # select * from Product
    data["products"] = products
    return render(request, "core/products/list.html", data)

# Crear un producto
def product_create(request):
    data = {"title1": "Productos", "title2": "Ingreso De Productos"}

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            messages.success(request, f"Éxito al crear el producto {product.description}.")
            return redirect("core:product_list")
    else:
        form = ProductForm()

    # Si el formulario no es válido o es una solicitud GET, mostrar el formulario con los datos actuales
    data["form"] = form
    return render(request, "core/products/form.html", data)

# Editar un producto
def product_update(request, id):
    data = {"title1": "Productos", "title2": "Edicion De Productos"}
    product = Product.objects.get(pk=id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, f"Éxito al actualizar el producto {product.description}.")
            return redirect("core:product_list")
    else:
        form = ProductForm(instance=product)
    data["form"] = form
    return render(request, "core/products/form.html", data)

# Eliminar un producto
def product_delete(request, id):
    product = Product.objects.get(pk=id)
    data = {"title1": "Eliminar",
            "title2": "Eliminar Un Producto", "product": product}
    if request.method == "POST":
        product.delete()
        return redirect("core:product_list")
    return render(request, "core/products/delete.html", data)

# ----------------- Vistas de Marcas -----------------
def brand_List(request):
    data = {"title1": "Marcas", "title2": "Consulta De Marcas De Productos"}
    brands = Brand.objects.all()
    data["brands"] = brands
    # Pasar los mensajes al contexto de la plantilla
    data["messages"] = messages.get_messages(request)
    return render(request, "core/brands/list.html", data)

# Crear una marca
def brand_create(request):
    data = {"title1": "Crear Marca", "title2": "Ingreso de Marca"}
    if request.method == "POST":
        form = BrandForm(request.POST)
        if form.is_valid():
            # Asignar el usuario actual al campo user de la marca
            brand = form.save(commit=False)
            brand.user = request.user
            brand.save()
            # Agregar mensaje de éxito
            messages.success(request, f"Éxito al crear la marca {brand.description}.")
            return redirect("core:brand_list")
    else:
        form = BrandForm()
    data["form"] = form
    return render(request, "core/brands/form.html", data)

# Editar una marca
def brand_update(request, id):
    data = {"title1": "Marcas", "title2": "Edicion De Marcas"}
    brand = Brand.objects.get(pk=id)
    if request.method == "POST":
        form = BrandForm(request.POST, request.FILES, instance=brand)
        if form.is_valid():
            form.save()
            # Agregar mensaje de éxito
            messages.success(request, f"Éxito al actualizar la marca {brand.description}.")
            return redirect("core:brand_list")
    else:
        form = BrandForm(instance=brand)

    data["form"] = form
    return render(request, "core/brands/form.html", data)

# Eliminar una marca
def brand_delete(request, id):
    brand = Brand.objects.get(pk=id)
    data = {"title1": "Eliminar", "title2": "Eliminar Una Marca", "brand": brand}
    if request.method == "POST":
        brand.delete()
        return redirect("core:brand_list")
    return render(request, "core/brands/delete.html", data)

# ----------------- Vistas de Proveedores -----------------
def supplier_List(request):
    data = {"title1": "Proveedores", "title2": "Consulta De Proovedores De Productos"}
    suppliers = Supplier.objects.all()
    data["suppliers"] = suppliers
    # Pasar los mensajes al contexto de la plantilla
    data["messages"] = messages.get_messages(request)
    return render(request, "core/suppliers/list.html", data)

# Crear un proveedor
def supplier_create(request):
    data = {"title1": "Proveedores", "title2": "Ingreso De Proveedores"}
    if request.method == "POST":
        form = SupplierForm(request.POST)
        if form.is_valid():
            supplier = form.save(commit=False)
            supplier.user = request.user  # Asignar el usuario actual al proveedor
            supplier.save()
            messages.success(request, f"Éxito al crear al proveedor {supplier.name}.")
            return redirect("core:supplier_list")
    else:
        form = SupplierForm()  # Mover esto aquí para que el formulario se cree en ambos casos
    # Pasar el formulario al contexto de la plantilla en ambos casos
    data["form"] = form
    return render(request, "core/suppliers/form.html", data)

# Editar un proveedor
def supplier_update(request, id):
    data = {"title1": "Proveedores", "title2": "Edicion De Proveedores"}
    supplier = Supplier.objects.get(pk=id)
    if request.method == "POST":
        form = SupplierForm(request.POST, request.FILES, instance=supplier)
        if form.is_valid():
            form.save()
            messages.success(request, f"Éxito al actualizar al proveedor {supplier.name}.")
            return redirect("core:supplier_list")
    else:
        form = SupplierForm(instance=supplier)
    data["form"] = form
    return render(request, "core/suppliers/form.html", data)

proy_sales/templates/core/suppliers/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<title>{% block title %} SGV - Crear Proveedores {% endblock title %}</title>

<section id="home-modulos" class="mt-4 d-flex justify-content-center align-items-center" data-aos="fade-up" data-aos-delay="200">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <div class="module-head">
                    <h2 class="title text-center">{{ title2 }}</h2>
                    <p>Complete el formulario para registrar un nuevo proveedor en el sistema.</p>
                </div>
            </div>
            <div class="form-container">
                <form id="supplier-form" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.address.id_for_label }}">{{ form.address.label }}</label>
                                {{ form.address }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="{{ form.ruc.id_for_label }}">{{ form.ruc.label }}</label>
                                {{ form.ruc }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                                {{ form.phone }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
                        {{ form.image }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.state.id_for_label }}">{{ form.state.label }}</label>
                        {{ form.state }}
                    </div>
                    <div class="form-group">
                        <div class="text-center">
                            <button type="submit" class="btn btn-details">
                                <i class="fa-solid fa-user-plus"></i>
                                Guardar
                            </button>
                            <a href="{% url 'core:supplier_list' %}" class="btn btn-cancel">
                                <i class="fa-solid fa-xmark"></i> Cancelar 
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- <script src="{% static 'js/validaciones.js' %}"></script> -->
{% endblock content %}

proy_sales/templates/core/suppliers/list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<title>{% block title %} SGV - Proveedores {% endblock title %}</title>

<section id="home-modulos" class="mt-4 d-flex justify-content-center align-items-center" data-aos="fade-up" data-aos-delay="200">
    <div class="container text-center">
        <div class="row">
            <!-- Mensaje de bienvenida a la izquierda -->
            <div class="col-lg-12">
                <div class="module-head">
                    <h2 class="title text-center">{{ title2 }}</h2>
                    <p>Agregue informacion de proveedores. </p>
                </div>
            </div>
            <div class="module-cards">
                <div class="row">
                    {% for item in suppliers %}
                    <div class="col-md-4 mb-4">
                        <div class="card card-custom">
                            <div class="card-header">
                                <h2 class="card-title">{{ item.name }}</h2>
                            </div>
                            <div class="card-body">
                                <img src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'img/default_person.png' %}{% endif %}" alt="Persona"><br>
                                <h3>RUC: <span class="info">{{ item.ruc }}</span></h3>
                                <h3>Dirección: <span class="info">{{ item.address }}</span></h3>
                                <h3>Celular: <span class="info">{{ item.phone }}</span></h3>
                                <h3>Creación: <span class="info">{{ item.created | date:"Y-m-d" }}</span></h3>
                                <h3>
                                    Estado: 
                                    {% if item.state %}
                                    <i class="fa-solid fa-check" style="color: green;"></i>
                                    {% else %}
                                    <i class="fa-solid fa-square-minus" style="color: red;"></i>
                                    {% endif %}
                                </h3>
                            </div> 
                            <div class="card-footer">
                                <a href="{% url 'core:supplier_update' item.id %}" class="btn btn-update"><i class="fa-solid fa-user-pen"></i> Editar</a>
                                <a href="#" class="btn btn-cancel" onclick="confirmDelete({{ item.id }})"><i class="fa-solid fa-trash"></i> Eliminar</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="form-group text-center mt-4">
                    <a class="btn btn-details" href="{% url 'core:supplier_create' %}"><i class="fa-solid fa-user-plus"></i> Nuevo proveedor </a>
                    <a class="btn btn-details" href="{% url 'home' %}"><i class="fa-solid fa-house"></i></a>
                </div>
            </div>
            <!-- AA -->
            
        </div>
    </div>
</section>
<body>
    <script>
        function confirmDelete(itemId) {
            DarkSwal.fire({
                title: '¿Estás seguro?',
                text: "¡No podrás revertir esto!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, eliminar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    const form = document.createElement('form');
                    form.method = 'POST';
                    form.action = `{% url 'core:supplier_delete' id=0 %}`.replace('0', itemId);
                    const csrfToken = document.createElement('input');
                    csrfToken.type = 'hidden';
                    csrfToken.name = 'csrfmiddlewaretoken';
                    csrfToken.value = '{{ csrf_token }}';
                    form.appendChild(csrfToken);
                    document.body.appendChild(form);
                    
                    // Mostrar mensaje de éxito
                    DarkSwal.fire({
                        title: '<span class="success-title">¡Éxito!</span>',
                        text: 'Se eliminó al proveedor correctamente.',
                        icon: 'success',
                        confirmButtonText: 'Aceptar'
                    }).then(() => {
                        // Envía el formulario después de confirmar el mensaje de éxito
                        form.submit();
                    });
                }
            });
        }
    </script>
</body>
{% endblock content %}